Refactored and prettified
Following better bash coding standards.
local readonly variables everywhere possible.
AWK scripts live in variables.
forloop variables now local.

diff --git a/bin/kackle b/bin/kackle
--- a/bin/kackle
+++ b/bin/kackle
@@ -5,7 +5,8 @@ if [[ $(uname) == "Darwin" ]];then
     PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
 fi
 
-command -v pandoc >/dev/null 2>&1 || { echo >&2 "I require Pandoc but it's not installed.  Aborting."; exit 1; }
+command -v pandoc >/dev/null 2>&1 \
+    || { echo >&2 "I require Pandoc but it's not installed.  Aborting."; exit 1; }
 
 ### GLOBAL VALUES
 PROD=1
@@ -51,22 +52,31 @@ new-post(){
     default_location="drafts"
     default_author="Ethan House"
 
+    local -r AWK_HEADERS=\
+'BEGIN   { FS=":"; OFS="\n"}
+        { printf "---\ntitle: %s\ndate: %s\nauthor: %s\nsummary: %s\n---", $1, $2, $3, "Example Blog Post" }
+END     { print "\nContent of my super awesome blog post!" }'
+
     read -p "Name of page: " p_title
     read -p "Location of page [$default_location]: " p_location
     read -p "Author [$default_author]: " p_author
 
     # Sets defaults if given value is NULL
-    p_location=${p_location:-$default_location}
-    p_author=${p_author:-$default_author}
-    p_date=$(gdate +"%B %d, %Y")
+    local -r p_location=${p_location:-$default_location}
+    local -r p_author=${p_author:-$default_author}
+    local -r p_date=$(gdate +"%B %d, %Y")
 
     # Ensures no illegal/bad characters are written to disk
-    p_ondisk=$(echo $p_title | tr " " - | tr '[:upper:]' '[:lower:]' | perl -p -e  's/[^A-Za-z0-9\-\.]//g;')
+    local -r p_ondisk=$(echo $p_title \
+        | tr " " - \
+        | tr '[:upper:]' '[:lower:]' \
+        | perl -p -e  's/[^A-Za-z0-9\-\.]//g;')
 
     # Ensures html safe encodings are used
-    p_title=$(echo $p_title | perl -n -mHTML::Entities -e ' ; print HTML::Entities::encode_entities($_) ;')
+    local -r p_title=$(echo $p_title \
+        | perl -n -mHTML::Entities -e ' ; print HTML::Entities::encode_entities($_) ;')
 
-    p_file="src/$p_location/$p_ondisk.md"
+    local -r p_file="src/$p_location/$p_ondisk.md"
 
     if [[ ! -d $(dirname $p_file) ]];then
         echo "Folder $(pwd)/$(dirname $p_file) doesn't exist. Can't Create $p_file"
@@ -74,10 +84,9 @@ new-post(){
     fi
 
     # Writes out template for new blog post
-    echo "$p_title:$p_date:$p_author" | awk \
-        'BEGIN  {FS=":"; OFS="\n"}
-                { printf "---\ntitle: %s\ndate: %s\nauthor: %s\nsummary: %s\n---", $1, $2, $3, "Example Blog Post" }
-        END     { print "\nContent of my super awesome blog post!" }' >> $p_file
+    echo "$p_title:$p_date:$p_author" \
+        | awk "$AWK_HEADERS" \
+        >> $p_file
 
     echo "File $(pwd)/$p_file Created Successfully"
 }
@@ -89,11 +98,14 @@ new-post(){
 #   Output folder
 ##########
 compile-folder() {
-    local SRC=$1
-    local OUT=$2
+    local -r SRC=$1
+    local -r OUT=$2
 
-    local MD_FILES=($(find -L $SRC -name "*.md"))
-    local BLD_FILES=($(sed "s@src@"${OUT}"@g;s@.md@.html@g" <<< ${MD_FILES[@]}))
+    local -r MD_FILES=($(find -L $SRC -name "*.md"))
+    local -r BLD_FILES=($(sed "s@src@"${OUT}"@g;s@.md@.html@g" <<< ${MD_FILES[@]}))
+
+    local i
+    local a
 
     if ! [[ -f $THEME ]]; then
         echo "Missing $THEME file"
@@ -114,10 +126,10 @@ compile-folder() {
         fi
     done
 
-    project_dest=$(sed "s/src/out/g" <<< $SRC)
+    local -r PROJECT_DEST=$(sed "s/src/out/g" <<< $SRC)
 
-    rsync -qrvzcl --delete "./static/"* "$project_dest"
-    printf "  COPY %s -> %s\n" "./static/" "$(readlink -f $project_dest)"
+    rsync -qrvzcl --delete "./static/"* "$PROJECT_DEST"
+    printf "  COPY %s -> %s\n" "./static/" "$(readlink -f $PROJECT_DEST)"
 }
 
 function format-page {
@@ -153,14 +165,22 @@ extract-headers(){
 #   Source folder to build
 ##########
 create-blogroll() {
-    local src="$1"
-    local title="$3"
+    local -r SRC="$1"
+    local -r TITLE="$3"
+    local -r AWK_HTML=\
+'{ gsub(".md",".html");
+printf "<h4 class=\"blog-roll\"> [%s](/%s) </h4>\n", $2, $5
+printf "<ul><li style=\"display:inline-block;margin-right:1em;\">_Written by %s_</li><li style=\"display:inline-block;margin-right:1em;\"><time>Posted on %s</time></li></ul>\n\n", $3, $1
+if ($3)
+    printf "%s\n\n", $4
+    print "---\n"}'
 
-    rm -f $src/index.md
+    local -r TMPFILE=$(mktemp)
+    local f
+    local a
 
-    local readonly TMPFILE=$(mktemp)
-    format-page "title: $title" > $TMPFILE
-    for f in "$src"/*.md;do
+    format-page "title: $TITLE" > $TMPFILE
+    for f in "$SRC"/*.md;do
         # If file is excluded then skip
         for a in ${EXCLUDE[@]:-}; do
             if [[ $i =~ $f ]]; then
@@ -168,16 +188,14 @@ create-blogroll() {
             fi
         done
         extract-headers "$f"
-    done | sort -k3nr -k1Mr -k2nr | sed "s@$(dirname $src)/@@g" | awk -F ':' \
-    '{ gsub(".md",".html");
-    printf "<h4 class=\"blog-roll\"> [%s](/%s) </h4>\n", $2, $5
-    printf "<ul><li style=\"display:inline-block;margin-right:1em;\">_Written by %s_</li><li style=\"display:inline-block;margin-right:1em;\"><time>Posted on %s</time></li></ul>\n\n", $3, $1
-    if ($3)
-        printf "%s\n\n", $4
-    print "---\n"}' | head -n -2 >> $TMPFILE
+    done | sort -k3nr -k1Mr -k2nr \
+        | sed "s@$(dirname $SRC)/@@g" \
+        | awk -F ':' "$AWK_HTML" \
+        | head -n -2 \
+        >> $TMPFILE
 
-    cp $TMPFILE $src/index.md
-    printf "  CREATE index.md -> %s\n" "$(readlink -f $src/index.md)"
+    cp $TMPFILE $SRC/index.md
+    printf "  CREATE index.md -> %s\n" "$(readlink -f $SRC/index.md)"
 }
 
 ##########
@@ -189,9 +207,9 @@ create-blogroll() {
 #   Sitename for sitemap.xml
 ##########
 finalize-webdir() {
-    local target=$1
-    local sitename=$2
-    local AWK_SCRIPT=\
+    local -r TARGET=$1
+    local -r SITENAME=$2
+    local -r AWK_SCRIPT=\
 'BEGIN { print "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\
 <urlset xmlns=\"http://www.sitemaps.org/schemas/sitemap/0.9\"\
         xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"\
@@ -200,7 +218,8 @@ finalize-webdir() {
     { printf "\t<url>\n\t\t<loc>%s</loc>\n\t\t<changefreq>weekly</changefreq>\n\t</url>\n", $NF }
 END { print "</urlset>"}'
 
-    local BLD_FILES=($(find -L $TARGET -name "*.html"))
+    local -r BLD_FILES=($(find -L $TARGET -name "*.html"))
+    local i
 
     for i in "${BLD_FILES[@]:-}"; do
         # If file is excluded then skip
@@ -209,24 +228,28 @@ END { print "</urlset>"}'
                 continue 2
             fi
         done
-        local fd=$(echo $i | sed "s@$target/@https://$sitename/@g")
+        local fd=$(echo $i \
+            | sed "s@$TARGET/@https://$SITENAME/@g")
         echo "$fd"
-    done | awk -F"\n" "$AWK_SCRIPT" > $target/sitemap.xml
+    done | awk -F"\n" "$AWK_SCRIPT" \
+        > $TARGET/sitemap.xml
 
-    printf "  CREATE sitemap.xml -> %s\n" "$(readlink -f $target/sitemap.xml)"
+    printf "  CREATE sitemap.xml -> %s\n" "$(readlink -f $TARGET/sitemap.xml)"
 
     if (("$PROD")) ;then
-        echo -e "User-Agent: *\nDisallow: /drafts/" > "$target/robots.txt"
-        printf "  CREATE PROD robots.txt -> %s\n" "$(readlink -f $target/robots.txt)"
+        echo -e "User-Agent: *\nDisallow: /drafts/" > "$TARGET/robots.txt"
+        printf "  CREATE PROD robots.txt -> %s\n" "$(readlink -f $TARGET/robots.txt)"
     else
-        echo -e "User-Agent: *\nDisallow: /" > "$target/robots.txt"
-        printf "  CREATE DEV robots.txt -> %s\n" "$(readlink -f $target/robots.txt)"
+        echo -e "User-Agent: *\nDisallow: /" > "$TARGET/robots.txt"
+        printf "  CREATE DEV robots.txt -> %s\n" "$(readlink -f $TARGET/robots.txt)"
     fi
 
     if (("$PROD"))  && [[ ! -z $(command -v htmlcompressor) ]];then
-        printf "  COMPRESSING %s\n" "$(readlink -f $target)"
-        command -v htmlcompressor >/dev/null 2>&1 || { echo >&2 "htmlcompressor required to compress $target folder!"; exit 1; }
-        find -L "$target" \( -name "*.html" -or -name "*.css" \) -exec htmlcompressor --compress-js --compress-css {} -o {} \;
+        printf "  COMPRESSING %s\n" "$(readlink -f $TARGET)"
+        command -v htmlcompressor >/dev/null 2>&1 \
+            || { echo >&2 "htmlcompressor required to compress $TARGET folder!"; exit 1; }
+        find -L "$TARGET" \( -name "*.html" -or -name "*.css" \) \
+            -exec htmlcompressor --compress-js --compress-css {} -o {} \;
     fi
 }
 
@@ -252,6 +275,7 @@ main() {
     # e: - Set Site Theme File Location.
     # o: - Sets output folder. Takes Valid Path
     #####
+
     while getopts ":hvdpo:b:r:t:T:N:x:f:e:" opt; do
         case $opt in
             p)
@@ -276,42 +300,35 @@ main() {
                 PROD=0
                 ;;
             o)
-                # Set output folder
-                OUTPUT="$OPTARG"
-                readonly OUTPUT
+                # Override default output folder
+                local -r OUTPUT_O="$OPTARG"
                 ;;
             e)
                 # Set Theme
-                THEME="$OPTARG"
+                local -r THEME_O="$OPTARG"
                 ;;
             f)
                 # Finialize folder for deployment
-                : ${TASK:="f"}
-                : ${TARGET:="$OPTARG"}
-                readonly TASK
-                readonly TARGET
+                local -r TASK="f"
+                local -r TARGET=$OPTARG
                 ;;
             b)
                 # Build Folder
-                : ${TASK:="b"}
-                : ${TARGET:="$OPTARG"}
-                readonly TASK
-                readonly TARGET
+                local -r TASK="b"
+                local -r TARGET=$OPTARG
                 ;;
             r)
                 # Create Blogroll
-                : "${TASK:=r}"
-                : "${TARGET:=$OPTARG}"
-                readonly TASK
-                readonly TARGET
+                local -r TASK="r"
+                local -r TARGET=$OPTARG
                 ;;
             T)
                 # Set title for blogroll
-                readonly BLOGROLL_TITLE="$OPTARG"
+                local -r BLOGROLL_TITLE="$OPTARG"
                 ;;
             N)
                 # Set sitename for Sitemap Generator
-                readonly SITENAME="$OPTARG"
+                local -r SITENAME="$OPTARG"
                 ;;
             x)
                 # Exclude folder from build process
@@ -332,10 +349,8 @@ main() {
     fi
 
     ### SET DEFAULTS AND READONLY STATUS
-    : "${OUTPUT:=out/}"
-    : "${THEME:=./theme/base.html}"
-    readonly OUTPUT
-    readonly THEME
+    local -r OUTPUT=${OUTPUT_O:-"out/"}
+    local -r THEME=${THEME_O:-"./theme/base.html"}
 
     # Test if target is a folder
     if ! [[ -d $TARGET ]]; then
